version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: data_viz_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app/server
      - ./client:/app/client

volumes:
  postgres_data: