version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_URL=${REDIS_URL}
      - PORT=3000
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "80:80"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
